import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { PostView } from "~/components/postview";
import { PageLayout } from "~/components/Layout";
import { generateSsgHelper } from "~/server/helper/ssgHelper";

const SinglePostPage: NextPage<{ id: string }> = ({ id }) => {

  const { data } = api.post.getPostById.useQuery({
    id,
  });

  if (!data) return <div>404 Not found</div>;

  console.log(data);

  return (
    <>
      <Head>
        <title>{`${data.post.content} - @${data.author.username}`}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <PostView {...data} />
      </PageLayout>
    </>
  );
};

export const getStaticProps: GetStaticProps = async (context) => {
  const ssg = generateSsgHelper()

  const id = context.params?.id;

  if (typeof id !== "string") throw new Error("No id");

  await ssg.post.getPostById.prefetch({ id });

  return {
    props: {
      trpcState: ssg.dehydrate(),
      id
    },
  };
};

export const getStaticPaths = () => {
  return {
    paths: [],
    fallback: "blocking",
  };
};

export default SinglePostPage;
